version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@0.0.4
  docker: circleci/docker@1.4.0

  executors:
    docker_build:
      machine:
        docker_layer_caching: true

jobs:
    build-deploy:
        executor: docker_build
        steps:
            - checkout
            - run:
                name: Build Image
                command: |
                    export TERM=xterm
                    ./breeze build-image --python 3.6 \
                    --assume-yes \
                    --install-airflow-version 1.10.11 \
                    --extras all \
                    --forward-credentials \
                    --backend mysql \
                    --github-organisation dejadavi-ks \
                    --github-repo airflow \
                    --additional-dev-deps "libasound2-dev" \
                    --additional-runtime-deps "libasound2" \
                    --install-airflow-reference master \
                    --production-image
            - run:
                name: Tag Image
                command: |
                    docker tag apache/airflow:master-python3.6 ${AWS_ECR_ACCOUNT_URL}/${AWS_ECR_REPO}

            - aws-ecr/ecr-login:
                region : us-east-1

            - aws-ecr/push-image:
                repo: ${AWS_ECR_ACCOUNT_URL}/${AWS_ECR_REPO}
                tag: latest
                            
workflows:
    build-deploy:
        jobs:
            - build-deploy
