version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@0.0.4
  docker: circleci/docker@1.4.0

jobs:
    build:
        working_directory: ~/project
        machine: true
        steps:
            - run:
                name: prepEnv
                command: |
                    sudo apt-get install util-linux coreutils
                    export PATH=/usr/local/opt/gnu-getopt/bin:$PATH
            - checkout
            - run:
                name: buildImage
                command: |
                    pwd && ls
                    ./breeze build-image --python 3.6 \
                    --install-airflow-version 1.10.11 \
                    --extras all \
                    --forward-credentials \
                    --additional-dev-deps "libasound2-dev" \
                    --additional-runtime-deps "libasound2" \
                    --install-airflow-reference master \
                    --production-image
                
workflows:
    build-deploy:
        jobs:
            - build
