version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@0.0.4
  docker: circleci/docker@1.4.0

jobs:
    build:
        machine: true
        steps:
            - checkout
            - run:
                name: Build Image
                command: |
                    apt get install util-linux coreutils
                    echo 'export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"' >> ~/.bash_profile . ~/.bash_profile
                    ~/.breeze
                    
workflows:
    build-deploy:
        jobs:
            - build
