version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@0.0.4
  docker: circleci/docker@1.4.0

jobs:
    build-deploy:
        working_directory: ~/project
        machine: true
        steps:
            - checkout
            - run:
                name: Build Image
                command: |
                    export TERM=xterm
                    ./breeze build-image --python 3.6 \
                    --assume-yes \
                    --install-airflow-version 1.10.11 \
                    --extras all \
                    --forward-credentials \
                    --backend mysql \
                    --github-organisation dejadavi-ks \
                    --github-repo airflow \
                    --additional-dev-deps "libasound2-dev" \
                    --additional-runtime-deps "libasound2" \
                    --install-airflow-reference master \
                    --production-image
            - aws-ecr/ecr-login:
                region : us-east-1
            - aws-ecr/push-image:
                repo: airflow
                tag: apache/airflow:master-python3.6
                            
workflows:
    build-deploy:
        jobs:
            - build-deploy
